function symbolic_y_ddot = func_y_ddot(alpha,alpha_dot,beta,beta_dot,u1,u2)
%FUNC_Y_DDOT
%    SYMBOLIC_Y_DDOT = FUNC_Y_DDOT(ALPHA,ALPHA_DOT,BETA,BETA_DOT,U1,U2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Jan-2024 17:01:16

t2 = cos(beta);
t3 = sign(alpha_dot);
t4 = sin(alpha);
t5 = sign(beta_dot);
t6 = sin(beta);
t7 = alpha_dot.^2;
t8 = beta.*2.0;
t9 = beta_dot.^2;
t15 = alpha_dot.*1.38567835997957e+17;
t16 = u1.*3.605720426696772e+22;
t10 = cos(t8);
t11 = sin(t8);
t12 = alpha+t8;
t17 = t3.*3.064862362692256e+19;
t19 = alpha_dot.*beta_dot.*t6.*6.970982569577989e+19;
t20 = t4.*1.027292593515467e+22;
t21 = t6.*t9.*3.485491284788995e+19;
t13 = sin(t12);
t14 = t10.*7.475390578688e-6;
t18 = -t17;
t22 = -t20;
t23 = t13.*2.113696580247056e+20;
t24 = t14-2.68836099268608e-3;
t25 = 1.0./t24;
et1 = beta_dot.*(-1.401543529857035e+17)+t5.*1.153830536542967e+19+t15+t16+t18+t19+t21+t22+t23-u2.*3.605720426696772e+22-beta_dot.*t2.*2.772465849896818e+16+t2.*t5.*2.28245194743242e+18;
et2 = t6.*t7.*3.485491284788995e+19+t7.*t11.*3.447415421401927e+18-t2.*u2.*7.132662335726312e+21;
et3 = beta_dot.*(-1.129061386313323e+18)+t5.*9.295077016214646e+19+t15+t16+t18+t19+t21+t22+t23-u2.*2.904711567567077e+23+sin(alpha+beta).*1.404165415235165e+22;
et4 = sin(alpha-beta).*(-1.036976407549701e+21)+alpha_dot.*t2.*2.741082135619622e+16-beta_dot.*t2.*5.544931699793635e+16-t2.*t3.*6.062762985367365e+18+t2.*t5.*4.56490389486484e+18;
et5 = t6.*t7.*2.80785686505812e+20+t7.*t11.*6.894830842803854e+18+t9.*t11.*3.447415421401927e+18+t2.*u1.*7.132662335726312e+21-t2.*u2.*1.426532467145262e+22;
et6 = alpha_dot.*beta_dot.*t11.*6.894830842803854e+18;
symbolic_y_ddot = [t25.*(et1+et2).*(-2.168404344971009e-24);(t25.*(et3+et4+et5+et6))./4.611686018427388e+23];
end
